language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-html5sass' ]; then cd .. && eval "mv $currentfolder generator-html5sass" && cd generator-html5sass; fi

